version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: forum-backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - PORT=8000

  frontend:
    build:
      context: ./ui-ux
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: forum-frontend
    volumes:
      - ./ui-ux:/app
    ports:
      - "8080:8080"
    environment:
      - API_LINK=http://backend:8000
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    restart: unless-stopped
    container_name: forum-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - frontend
