version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: forum-backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - SECRET_KEY=${SECRET_KEY}

  frontend:
    build:
      context: ./ui-ux
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: forum-frontend
    volumes:
      - ./ui-ux:/app
    ports:
      - "8080:8080"
    environment:
      - API_LINK=http://localhost:8000
    depends_on:
      - backend